[package]
name = "rustanel"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
eframe = { version = "0.22.0" }
env_logger = "0.10.0"
enum-map = "2.6.3"
lazy_static = "1.4.0"
